package com.example.adaptive_nav_cmp.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFFD32F2F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDAD6)
val LightOnPrimaryContainer = Color(0xFF410002)
val LightSecondary = Color(0xFF775656)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDAD6)
val LightOnSecondaryContainer = Color(0xFF2C1516)
val LightTertiary = Color(0xFF715B2E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDEA6)
val LightOnTertiaryContainer = Color(0xFF261A00)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF201A1A)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF201A1A)
val LightSurfaceVariant = Color(0xFFF5DDDB)
val LightOnSurfaceVariant = Color(0xFF534341)
val LightOutline = Color(0xFF857371)

val DarkPrimary = Color(0xFFFFB4AB)
val DarkOnPrimary = Color(0xFF690005)
val DarkPrimaryContainer = Color(0xFF93000A)
val DarkOnPrimaryContainer = Color(0xFFFFDAD6)
val DarkSecondary = Color(0xFFE7BDB9)
val DarkOnSecondary = Color(0xFF442929)
val DarkSecondaryContainer = Color(0xFF5D3F3F)
val DarkOnSecondaryContainer = Color(0xFFFFDAD6)
val DarkTertiary = Color(0xFFE4C38C)
val DarkOnTertiary = Color(0xFF3F2E04)
val DarkTertiaryContainer = Color(0xFF574419)
val DarkOnTertiaryContainer = Color(0xFFFFDEA6)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF201A1A)
val DarkOnBackground = Color(0xFFECE0DF)
val DarkSurface = Color(0xFF201A1A)
val DarkOnSurface = Color(0xFFECE0DF)
val DarkSurfaceVariant = Color(0xFF534341)
val DarkOnSurfaceVariant = Color(0xFFD8C2BF)
val DarkOutline = Color(0xFFA08C8A)
